package graph_package

import "sync"

// These are the types used in computing

type Graph struct {
	totalNumberOfVertexes int
	Vertexes              map[VertexIdType]*Vertex
	SuperStep             int
}

type Vertex struct {
	Id                          VertexIdType
	Value                       VertexValue
	Edges                       map[EdgeIdType]*Edge
	ReceivedMessagesInSuperStep map[int][]PregelMessage
	messageMutex                sync.Mutex
	MessagesToSend              map[VertexIdType][]PregelMessage
	VotedToHalt                 bool
	numSuperSteps               int
	HasSentMessages             bool
}

type Edge struct {
	Id    EdgeIdType
	To    VertexIdType
	Value EdgeValue
}

// These are the types used in communication and IO

type CommunicationGraph struct {
	Vertexes map[VertexIdType]CommunicationVertex
	// Do NOT use these fields on the input graph!
	TotalNumberOfVertexes int
	NextSuperStep         int
	AutoGenerated         bool
}

type CommunicationVertex struct {
	Id               VertexIdType
	Value            VertexValue
	Edges            map[EdgeIdType]CommunicationEdge
	IncomingMessages []PregelMessage
	VotedToHalt      bool
}

type CommunicationEdge struct {
	Id    EdgeIdType
	To    VertexIdType
	Value EdgeValue
}
